# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShopMall' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ShopMall
  pod 'Masonry', '1.0.1'

end
